### PR TITLE
Repaired 41 internal hyperlinks due to incorrect filenames

### PR DESCRIPTION
**Pull request by s3170**
The changed files had broken internal hyperlinks as they were pointing to local files "judge_..." when those files had been renamed.  I figured out which files these links were supposed to point to, and corrected them. 41 internal hyperlinks corrected.  Pls review and accept this pull request. This repo has not been updated for a few years.

### CODE REVIEW

**Comment by jazinheira** [comment]
Thanks, @s317! We'll try to review this in the next few days.

@athuggins Did you get a notification about this PR?

**Comment by s3170** [comment]
Thanks @jazinheira and @athuggins! This is my first (ever) contribution to an existing open educational resource and I'm curious to see it come into effect.

**Comment by jazinheira** [comment]
This looks like good work! I've pointed the PR to a bug branch; I want to double check on what we have to do regarding attribution and versioning before merging into master.

Were you using vim to find and replace the links?

**Comment by s3170** [comment]
Yes, I usually use vim as my text editor for munging textual data.  In the case of this pull request, after realizing the broken links were due to a systematic error (due to changes in filenames), I used "grep" and "sed" to search across all html files for the pattern of the error, and arrive at a machine readable list of files with errors, the incorrect strings in href tags, and the correct string to insert into the href tag.  Using the list, I just ran a series of search-and-replace commands in vim for each of the files with errors.  This could be fairly automated, after testing and confirming that the commands made sense.  (I'm a higher-education educator and administrator, interested in open pedagogy and open resources.)

**Pull request merged**
